settings:
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 0
  host: ""
schema:
  - name: space-go
    path: ./src
    commands:
      fmt:
        status: true
      install:
        status: true
      run:
        status: true
    watcher:
      paths:
        - /src
      extensions:
        - go
      ignored_paths:
        - .git
        - .realize
        - vendor
